sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t sajalgupta06/app .
  - docker build -t sajalgupta06/nginx ./nginx
 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sajalgupta06/app
  - docker push sajalgupta06/nginx


deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: safar
  env: Safar-env
  bucket_name: elasticbeanstalk-eu-north-1-195612002133
  bucket_path: safar
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY